sudo: false
language: cpp
cache:
  directories:
    - $HOME/ccache
before_install: mkdir -p ${HOME}/.local/bin/
matrix:
  include:
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-4.9', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python3', 'virtualenv', 'libxml2-utils']
      install: export CXX="g++-4.9" CC="gcc-4.9"

    - os: linux
      compiler: gcc-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-5', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python3', 'virtualenv', 'libxml2-utils']
      install: export CXX="g++-5" CC="gcc-5"

    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-7', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python3', 'virtualenv', 'libxml2-utils']
      install: export CXX="g++-7" CC="gcc-7"

    # - os: linux
    #   compiler: clang-3.8
    #   addons:
    #     apt:
    #       sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports' , 'llvm-toolchain-precise-3.8']
    #       packages: ['clang-3.8', 'g++-4.9', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python3', 'virtualenv'] # g++ required for newer libstdc++
    #   install: export CXX="clang++-3.8" CC="clang-3.8"

    # clang-3.9 currently not white listed.
    - os: linux
      compiler: clang-3.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports' , 'llvm-toolchain-precise-3.9']
          packages: ['clang-3.9', 'g++-7', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python3', 'virtualenv', 'libxml2-utils'] # g++ required for newer libstdc++
      install: export CXX="clang++-3.9" CC="clang-3.9"

    - os: linux
      compiler: clang-7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports', 'llvm-toolchain-trusty-7']
          packages: ['clang-7', 'g++-7', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python3', 'virtualenv', 'libxml2-utils'] # g++ required for newer libstdc++
      install: export CXX="clang++-7" CC="clang-7"

# currently too slow on osx
    #- os: osx
      #compiler: clang-3.6
      #before_install:
        #- sudo brew update
        #- sudo brew tap homebrew/versions
        #- sudo brew install llvm36
      #install: ['export CXX="clang++-3.6" CC="clang-3.6"' ]

    #- os: osx
      #compiler: clang-3.7
      #before_install:
        #- sudo brew update
        #- sudo brew tap homebrew/versions
        #- sudo brew install llvm37
      #install: ['export CXX="clang++-3.7" CC="clang-3.7"' ]

before_script:
  - export PATH=$HOME/.local/bin:/usr/lib/ccache:$PATH
  - mkdir -p venv
  - virtualenv -p python3 venv
  - source venv/bin/activate
  - pip install -r manual/requirements.txt
  - pip install cmake
  - rm -rf ${HOME}/.ccache
  - mkdir -p ${HOME}/ccache/${TRAVIS_BRANCH}/${TRAVIS_OS_NAME}/${CXX}
  - ln -s  ${HOME}/ccache/${TRAVIS_BRANCH}/${TRAVIS_OS_NAME}/${CXX} ${HOME}/.ccache
  - ln -s /usr/bin/ccache ${HOME}/.local/bin/${CXX}
  - ln -s /usr/bin/ccache ${HOME}/.local/bin/${CC}
script:
  - ccache -s
  - ./util/travis/linux-cibuild.sh
  - ccache -s
