sudo: false
language: cpp
compiler:
  - gcc-4.8
  - clang
cache:
  apt: true
  directories:
  - _build
install:
  - if [ "$CC" == "gcc" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
addons:
  apt:
    packages:
    - cmake
    - python
    - python-nose
    - zlib1g-dev
    - libbz2-dev
    - libboost-dev
    - python-jinja2
    - python-pip
    - gcc-4.8
    - g++-4.8
    - clang
before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install -r manual/requirements.txt --user `whoami`
script:
  ./util/travis/linux-cibuild.sh
