name: Workflow to deploy dox for SeqAn

on:
  push:
    branches:
      - master
      - develop

jobs:
  my_job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup python 3 environment
        uses: actions/setup-python@v1.1.1

      - name: install dox requirements
        shell: bash
        run: pip install -r manual/requirements.txt

      - name: intialise and build dox
        shell: bash
        run: |
          cd dox
          cp dox_only.sh.in dox_only.sh
          chmod 775 dox_only.sh
          ./dox_only.sh

      - name: deploy
        uses: Pendect/action-rsyncer@master
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          BRANCH: ${GITHUB_REF#refs/heads/}
        with:
          flags: '-avzr --delete'
          src: 'dox/html/'
          dest: '$REMOTE_USER@$REMOTE_HOST:$TARGET/$BRANCH'
